# Generated by Django 4.2.13 on 2025-12-04 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Course code (e.g., CS101)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Course name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('semester', models.CharField(help_text='Semester (e.g., Fall 2023)', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=50, help_text='Maximum number of students')),
                ('enrolled_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('code', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Material title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Material description')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('file_url', models.URLField(blank=True, help_text='External file URL')),
                ('material_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'Link'), ('assignment', 'Assignment'), ('other', 'Other')], default='document', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Whether material is required')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('content', models.TextField(help_text='Announcement content')),
                ('is_pinned', models.BooleanField(default=False, help_text='Whether announcement is pinned')),
                ('is_urgent', models.BooleanField(default=False, help_text='Whether announcement is urgent')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('request_message', models.TextField(blank=True, help_text="Student's request message")),
                ('response_message', models.TextField(blank=True, help_text="Lecturer's response message")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Session title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Session description')),
                ('scheduled_date', models.DateField(help_text='Date of the session')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('location', models.CharField(help_text='Classroom location', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Location latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Location longitude', max_digits=9, null=True)),
                ('geofence_radius', models.PositiveIntegerField(default=100, help_text='Geofence radius in meters')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether attendance is mandatory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time'],
                'unique_together': {('course', 'scheduled_date', 'start_time')},
            },
        ),
    ]
